version: 2
jobs:
  test36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: install
          command: sudo ./dev/install.sh
      - run:
          name: test
          command: pytest
  tests:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: install
          command: sudo ./dev/install.sh
      - run:
          name: flake8
          command: flake8
      - run:
          name: test
          command: pytest --cov
      - run:
          name: upload coverage
          command: bash <(curl -s https://codecov.io/bash)
  deploy-release:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: install-dev
          command: sudo ./dev/install-dev.sh
      - run:
          name: validate version
          command: agilekit git validate
      - run:
          name: build bundles
          command: sudo python setup.py sdist bdist_wheel
      - run:
          name: upload release
          command: twine upload dist/* --username lsbardel --password $PYPI_PASSWORD
      - run:
          name: create tag
          command: agilekit git release --yes

workflows:
  version: 2
  build-deploy:
    jobs:
      - tests
      - test36
      - deploy-release:
          requires:
            - tests
            - test36
          filters:
            branches:
              only: deploy
            tags:
              ignore: /.*/
